
# Project information
site_name: Portfolio Performance Manual

docs_dir: ../../docs/en
site_dir: ../../site/en

site_description: Manual of Portfolio Performance
site_author: Andreas Buchen, et. al.
site_url: https://help.portfolio-performance.info/en/

repo_name: portfolio-performance/portfolio-help
repo_url: https://github.com/portfolio-performance/portfolio-help
edit_uri: tree/master/docs/en/

copyright: This work is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.

theme:
  name: material
  custom_dir: ../../overrides/
  palette:
    primary: light green
    accent: amber
  features:
    - content.code.annotate 
    - content.code.copy
    - navigation.indexes
    - navigation.
    - content.action.edit
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  language: en

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  alternate:  
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

  social:
    - icon: material/home
      link: https://www.portfolio-performance.info
    - icon: fontawesome/brands/github
      link: https://github.com/portfolio-performance/portfolio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/portfolioperf
    - icon: fontawesome/solid/comments
      link: https://forum.portfolio-performance.info
    - icon: material/bug
      link: https://github.com/portfolio-performance/portfolio/issues

plugins:
  - search:
      lang: en
  - caption:
      figure:
        caption_prefix: 'Figure {index}. '
        position: top
        markdown_identifier: 'Figure:'
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables

nav:
  - About this manual: index.md
  - Getting started:
      - Getting started: getting-started/index.md
      - Installation: getting-started/installation.md
      - Creating your portfolio: getting-started/create-portfolio.md
      - Adding securities: getting-started/adding-securities.md
      - Managing your portfolio:
          - Managing your portfolio: getting-started/manage-portfolio/index.md
          - Making a Deposit: getting-started/manage-portfolio/deposit.md
          - Buying securities: getting-started/manage-portfolio/buy.md 
          - Selling securities: getting-started/manage-portfolio/sell.md 
          - Recording a delivery: getting-started/manage-portfolio/delivery.md
          - Dividend payment: getting-started/manage-portfolio/dividend.md 
          - Bonds: getting-started/manage-portfolio/bonds.md
          - Measure Performance: getting-started/measure-performance.md
  - Basic concepts:
      - Basic concepts: concepts/index.md
      - Financial terminology: concepts/financial-terminology.md
      - Account: concepts/account.md
      - Transaction: concepts/transaction.md
      - Reporting period: concepts/reporting-period.md
      - Purchase value: concepts/purchase-value.md
      - Performance:
          - Performance: concepts/performance/index.md
          - Money-weighted return: concepts/performance/money-weighted.md
          - Time-weighted return: concepts/performance/time-weighted.md
  - How-to:
      - How-to: how-to/index.md
      - Importing CSV-files: how-to/importing.md
      - Reinvesting dividends: how-to/reinvesting-dividends.md
      - Import fund data from Morningstar: how-to/morningstar.md
      - Hack data file to add defauly Quote Feed: how-to/quote-feed.md
      - Copy securities between portfolios: how-to/copy-securities.md
  - Reference manual:
      - Reference manual: reference/index.md
      - File Menu:
          - New: reference/file/new.md
          - Save: reference/file/save.md
          - Export: reference/file/export.md
      - View Menu:
          - Options: reference/view/options.md
          - Settings: reference/view/settings.md
          - Performance: reference/view/performance.md
          - Reports:
              - Statement of Assets: reference/view/reports/statement.md
              - Chart: reference/view/reports/statement-chart.md
              - Holdings: reference/view/reports/holdings.md
      - Help Menu:
          - Check for Updates: reference/help/check-updates.md
          # - About Portfolio Performance: reference/help/about.md

