
# Project information
site_name: Portfolio Performance Manual

docs_dir: ../../docs/en
site_dir: ../../site/en

site_description: Manual of Portfolio Performance
site_author: Andreas Buchen, et. al.
site_url: https://help.portfolio-performance.info/en/

repo_name: portfolio-performance/portfolio-help
repo_url: https://github.com/portfolio-performance/portfolio-help
edit_uri: blob/master/docs/

copyright: This work is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.

theme:
  name: material
  custom_dir: ../../overrides/
  palette:
    primary: light green
    accent: amber
  features:
    - content.code.annotate 
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  language: en

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  alternate:  
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

  social:
    - icon: material/home
      link: https://www.portfolio-performance.info
    - icon: fontawesome/brands/github
      link: https://github.com/portfolio-performance/portfolio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/portfolioperf
    - icon: fontawesome/solid/comments
      link: https://forum.portfolio-performance.info
    - icon: material/bug
      link: https://github.com/portfolio-performance/portfolio/issues
  analytics:
    provider: google
    property: G-9F7652B62Z

plugins:
  - search:
      lang: en
  - caption:
      figure:
        caption_prefix: 'Figure {index}. '
        position: top
        markdown_identifier: 'Figure:'

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - attr_list
  - md_in_html
  - tables

nav:
  - About this manual: index.md
  - Getting started:
      - Getting started: getting-started/index.md
      - Installation: getting-started/installation.md
      - Creating your portfolio: getting-started/create-portfolio.md
      - Adding securities: getting-started/adding-securities.md
      - Managing your portfolio:
          - Managing your portfolio: getting-started/manage-portfolio/index.md
          - Making a Deposit: getting-started/manage-portfolio/deposit.md
          - Buying securities: getting-started/manage-portfolio/buy.md 
          - Selling securities: getting-started/manage-portfolio/sell.md 
          - Dividend payment: getting-started/manage-portfolio/dividend.md 
  - Basic concepts:
      - Basic concepts: concepts/index.md
      - Financial terminology: concepts/financial-terminology.md
      - Account: concepts/account.md
      - Transaction: concepts/transaction.md
      - Reporting period: concepts/reporting-period.md
      - Purchase value: concepts/purchase-value.md
      - IRR: concepts/irr-theory.md
      - IRR example: concepts/irr-example.md
  - Common procedures:
      - Common procedures: procedures/index.md
      - Importing CSV-files: procedures/importing.md
      - Reinvesting dividends: procedures/reinvesting-dividends.md
  - Tips & tricks:
      - Tips & tricks: tricks/index.md
      - Import fund data from Morningstar: tricks/morningstar.md

