backend:
  name: github
  repo: buchen/portfolio-help
  branch: master

publish_mode: editorial_workflow

public_folder: "images/uploads"
media_folder: "docs/images/uploads"

collections:
  - name: "page"
    label: "Page"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
